spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_manager?serverTimezone=UTC
    username: root
    password: root

# 模板引擎
  thymeleaf:
    cache: false


  application:
    name: yy-custom

  cloud:
    loadbalancer:        # 打开重试机制
      retry:
        enabled: true


mybatis:
  type-aliases-package: com.yy.bean

# 注册
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://166.166.0.199:1998/eureka
      # defaultZone: http://166.166.166.166:10086/eureka,http://166.166.166.166:10087/eureka

# 重试
yy-server:
  ribbon:
    ConnectTimeout: 250   #  Ribbon的连接超时时间
    ReadTimeout: 1000    #  Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true #  是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1   #  切换实例的重试次数
    MaxAutoRetries: 1  #  对当前实例的重试次数

# 熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutlnMillisecond: 6000   #设置hystrix的超时时间为6000ms



server:
  port: 1998
